### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ApostolosZ** [marcos-diazg/musica#31] opened 2018-08-16 07:13 UTC
I have uploaded 109 files trying to run mutational signatures analysis, but an error occurs and I cannot get the results. it seems that the server is very busy?

**Comment by marcos-diazg** [comment] 2018-08-16 08:28
Hello!

First of all, thank you for using our app! Regarding the issue you commented, it could be that server is busy but I would expect that probably the problem is regarding file input. Are you correctly selecting file type and genome build for the whole set of samples? Try to perform the analysis with a subset of the samples, and then incresasing the number in order to know if the issue is due to one specific file. Please, do not hesitate to contact me again if you keep facing the same error.

**Comment by ApostolosZ** [comment] 2018-08-16 20:11
Thanks for the prompt reply. Actually, the vcf files are downloaded from
the TCGA, so I doubt that there's a problem with them. I tried uploading a
subset of the files and it works fine. However, once I upload ~60-70 vcf
files I keep receiving the ERROR notification.

**Comment by marcos-diazg** [comment] 2018-08-20 14:46
Ok, so if you are using VCF files from TCGA then the problem probably should be related with our server capacity or regarding the application limit for input files (which is fixed in 1GB). Sorry about that.

You can try to perform separated analysis for different set of samples or to use MAF files from TCGA, which group all samples available from a specific cancer type. Another option could be to consider using MuSiCa from your own computer/server following the procedure commented in the [README of our repository](https://github.com/marcos-diazg/musica).

**Closed** 2018-10-24 09:12 UTC
